dataloader:
  batch_size: 4
  dataset:
    cls: "DetectionDataset"
    image_dir: "{root}/{dataset}/{split}/images"
    label_dir: "{root}/{dataset}/{split}/labels"
    transform_params:
      Resize:
        size: 512
      RandomHorizontalFlip: 
        p: 0.1
      RandomVerticalFlip:
        p: 0.1
      ColorJitter:
        brightness: 0.0
        contrast: 0.0
        hue: 0.0
        saturation: 0.0
train:
  input_image_size: 512
  num_classes: 1203
  anchors: 
    - [10, 13, 16, 30, 33, 23] # stride 8
    - [30, 61, 62, 45, 59, 119] # stride 16
    - [116, 90, 156, 198, 373, 326] # stride 32
  strides: [8, 16, 32]
